### PR TITLE
Update readme

### LINKED ISSUE #11: Add slides to README

### PR DESCRIPTION
**Pull request by shiryz**
- Adds slides
- adds corresponding slide number where it corresponds.
Fixes #11 .

### CODE REVIEW

**Review by ZooeyMiller — CHANGES_REQUESTED** [review]
The addition of the slides looks all good, but would ask the changes requested in #4 #6 #8 #10 be made before approving this since it also contains all of those changes.

**Comment by shiryz** [comment]
@ZooeyMiller, I've merged all the changes into this branch if you want to look at one pr

**Review by ZooeyMiller — APPROVED** [review]
:sparkles:

**Review by macintoshhelper — APPROVED** [review]
Looks good. Explains why a database is needed. Having something on static file vs database might be nice (doesn't scale well), but might go into too much detail. Going through some examples of basic schemas together is good.

**Comment by shiryz** [comment]
@ZooeyMiller merge please if this is what you did for facg2

**Comment by ZooeyMiller** [comment]
This is more or less what I did for FACG2, a little different just because we got in late (crossing took longer than expected) and one of the local mentors had done a brief run through of databases already, so we talked more about theory. 

But yes, all good, so will merge.

**Pull request merged**
